config/routes.rb
Rails.application.routes.draw do
  
  get "user/new"
  get "login" => "user#login"
  post "login" => "user#login_form"
  post "logout" => "user#logout" 
  


  get "quizzes/new" => "quizzes#new"
  post "quizzes/create" => "quizzes#create"

  get "quizzes/index" => "quizzes#index"
  get "quizzes/:id" => "quizzes#show", as: :quiz
  post "quizzes/:id/check_answer", to: "quizzes#check_answer"
  post "quizzes/index", to: "quizzes#index"


 
  get "user/index" => "user#index"

  get "/" => "home#top"









  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :quiz
  #belongs_to :user, optional: true  # user_id が nil でも許容される

  validates :user_answer, {presence: true, length:{maximum: 50}}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
  

end

app/models/quiz.rb
class Quiz < ApplicationRecord
  has_one :answer, dependent: :destroy
  accepts_nested_attributes_for :answer

  belongs_to :user
  validates :question, {presence: true, length:{maximum: 250}}
  validates :answer_1, {presence: true, length:{maximum: 50}}
  validates :answer_2, {presence: true, length:{maximum: 50}}
  validates :title, {presence: true, length:{maximum: 50}}
  
  # Quiz_result中間テーブルの紐付け
  has_many :quiz_results
  has_many :users, through: :quiz_results

  validates :select_button_value, presence: true

end

app/models/quiz_result.rb
class QuizResult < ApplicationRecord
  belongs_to :user
  belongs_to :quiz
end

app/models/user.rb
class User < ApplicationRecord
  has_many :quizzes, dependent: :destroy

  # メールアドレスのバリデーション
  # 空白を許可しない、同じメールアドレスを許可しない　メールアドレスの形式をチェック
  validates :email, presence: true, uniqueness: true,  format: { with: URI::MailTo::EMAIL_REGEXP }
    
  # Quiz_result中間テーブルの紐付け
  has_many :quiz_results
  has_many :quizzes, through: :quiz_results
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.

  allow_browser versions: :modern
  before_action :set_current_user

  def set_current_user
    # @current_user = User.find_by(id: session[:user_id])
    @current_user = User.find(session[:user_id]) if session[:user_id]
    rescue ActiveRecord::RecordNotFound
    @current_user = nil
  end
  
  def set_quiz
    @quiz = Quiz.new
  end

  def quiz_check_answer
    @quiz = Quiz.find_by(id: params[:id])
    selected_answer = params[:selected_answer]
    @current_user
    # ↑変数入れなくて良い
    if @quiz && selected_answer
      if @current_user
        elapsed_time = (Time.current - @quiz.started_at).to_i # 経過時間（秒単位）
        # 秒数を時間、分、秒の形式に変換
        time_in_hours = Time.at(elapsed_time).utc.strftime("%H:%M:%S")

        # 中間テーブルログインしているユーザーIDと開いているクイズIDの紐付け
        quiz_result = QuizResult.find_or_create_by(user: @current_user, quiz: @quiz) 
        
        if selected_answer == @quiz.answer.user_answer
          
          # 中間テーブル
          #毎回０にして新しいデータを保存するので　if 小さい　＞　大きい　で保存する時の条件をつける
          #if quiz_result.time_spent.nil? || quiz_result.time_spent >= elapsed_time
          if quiz_result.time_spent >= elapsed_time
            quiz_result.time_spent = 0
            quiz_result.time_spent = elapsed_time.to_i
            quiz_result.save
          end

          # QuizResultに保存（ユーザーとクイズごとの解答時間を管理）
          # セーブをアップデート文に買える　１１２５
          @current_user.update(
             # ユーザーに正解したらスコア+1
            score: @current_user.score.to_i + 1,   # ユーザーに正解したらスコア+1

            # total_time が nil の場合は 0 に設定してから秒単位で加算
            total_time: (@current_user.total_time || 0.0) + elapsed_time.to_i  
          )
        
          
          # ユーザーに正解したらスコア+1
          #@user.score = @user.score.to_i + 1
          #@user.save # スコアをデータベースに保存  
          #flash[:notice] = "正解 : #{time_in_hours}"
          # total_time が nil の場合は 0 に設定してから秒単位で加算
          #@user.total_time ||= 0.0
          #@user.total_time += elapsed_time.to_i # 秒単位で加算
          #@user.save
          
          redirect_to("/quizzes/new")
          
        else selected_answer != @quiz.answer.user_answer
          flash[:notice] = "不正解"
          redirect_to("/quizzes/new")
        end
      else
        # ログインなし状態の処理
        if selected_answer == @quiz.answer.user_answer
          flash[:notice] = "正解"
          return redirect_to("/quizzes/new")
        else selected_answer != @quiz.answer.user_answer
          flash[:notice] = "不正解"
          return redirect_to("/quizzes/new")
        end
      end
        
    end
  end

  def quiz_find_id
    @quiz = Quiz.find_by(id: params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
    @quiz = Quiz.all
  end
end


# <%= link_to image_tag("Bg01.jpg"), "/quizzes/index"%>

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :set_quiz, only: [:new]
  before_action :quiz_check_answer, only: [:check_answer]
  before_action :quiz_find_id, only: [:show]

  def new
  end

  def create
    @quiz = Quiz.new(
      question: params[:question], 
      answer_1: params[:answer_1],
      answer_2: params[:answer_2],
      title: params[:title],
      user_id: @current_user.id,   # .id忘れずに！
      # quizテーブルに書いた、accepts_nested_attributes_for を使用することで、Quiz の作成時に Answer のデータも同時に保存できます。
      answer_attributes: { 
      user_answer: params[:user_answer]
      },
      # 新しく追加したセレクトボタンの値
      select_button_value: params[:select_button_value]

    )
    if 
      @quiz.save
      redirect_to("/quizzes/index")

    else
      redirect_to("/quizzes/new")
      flash[:notice] = "入力に誤りがあるみたいです"
      # render :new
    end
  
  end

  def index

    # 現在のページを取得、デフォルトは１
    current_page = (params[:page] || 1).to_i
    # 1ページに表示するクイズの数
    per_page = 6
  
    # セレクトボタン　名前はname属性使用
    select_option = params[:select_option]

    # クイズの取得条件
    if select_option.present? && select_option != "全体"
      # セレクトボタンの値に応じたクイズを取得　Quiz.whereを使用しカラムセレクトボタンと送信されたセレクトボタンの紐づけ
      @quiz = Quiz.where(select_button_value: select_option).offset((current_page - 1) * per_page).limit(per_page)
    else
      # クイズをページに応じて取得する
      @quiz = Quiz.order(created_at: :asc).offset((current_page -1)* per_page).limit(per_page)
    end
    
    # クイズの総数を計算（フィルタリング後のデータ数を取得）total_quizzes = select_option.present? ?Quiz.where...ryの書き方もあったけどわからなくなるのでこちらを使用
    if select_option.present? && select_option != "全体"
      total_quizzes = Quiz.where(select_button_value: select_option).count
    else
      total_quizzes = Quiz.count
    end
    
    # 最後のページの判定
    @is_last_page = (current_page * per_page) >= total_quizzes

    # 次へボタン用のページ番号
    @next_page = current_page + 1 

    # 戻るボタン用のページ番号ただし、1ページ目は戻れない）
    @prev_page = current_page - 1 if current_page > 1


  end

  def show
    @quiz = Quiz.find_by(id: params[:id])
    @options = [@quiz.answer_1, @quiz.answer_2, @quiz.answer.user_answer].shuffle 
    @quiz.started_at = Time.current
    @quiz.save



    if @quiz
      # クイズに関連するQuizResultをtime_spent
      @quiz_result = QuizResult.where(quiz: @quiz).order(:time_spent).limit(3)
    else
      # each文の中身がnullだった場合こちらでnullエラーを防ぎます
      @quiz_result = []
    end
      
  end
    
    
  

  def check_answer
  end
  
  private
  # 秒数を "HH:MM:SS" 形式の文字列に変換するメソッド
  def seconds_to_time(seconds)

  hours = seconds / 3600

  minutes = (seconds % 3600) / 60

  seconds = seconds % 60

  format("%02d:%02d:%02d", hours, minutes, seconds)
  
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  
  def index
    @users = User.order(score: :desc) 
    

  end


 #ログイン画面
  def login
  end

  #ログインした時の処理
  def login_form
    @user = User.find_by(name: params[:name],email: params[:email])
    session[:user_id] = @user.id
    if @user
      redirect_to("/quizzes/index")
    else
      render("users/login")
    end
  end

  def logout  
    @a = "ログインしてくださいaaaaaaaaaaa"
    session[:user_id] = nil
    redirect_to("/login")
  end

  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/home/top.html.erb
<!DOCTYPE html>

<html>
  <head>
  </head>

  <body>
  <h1>ようこそ</h1>
  <p>ログイン登録して投稿できるようにしよう！</p>
    <diiv class="top_main">
      <div class="top_options_container">
        <% @quiz.sample(3).each do |quiz|%>
          <div class="top_option_2">
            <%=link_to(quiz.title, "/quizzes/#{quiz.id}show")%>
             <p><%= quiz.question%></p>
          </div>
         <% end %>
      </div>
    </div>  
    <div class="top_footer">
    </div>

  </body>
  
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>





  <body>
    <div class="header">
      <div class="header-logo">Quiz掲示板</div>
        <div class="header_login">
          <% if @current_user %>
            <%= button_to("ログアウト", "/logout", {method: "post"})%> 
          <% else %>
            <%= button_to("ログイン", "/login", {method: "get"})%>
          <% end %>
        </div>
        <div class="header_link">
            <% if session[:user_id] %>    
              <div class="user_name"><%= session[:user_id] %></div>
              <li><%= link_to("トップページ","/")%></li>
              <li><%= link_to("新規投稿作成", "/quizzes/new")%></li>
              <li><%= link_to("ユーザー一覧", "/user/index")%></li>
              <li><%= link_to("投稿","/quizzes/index")%></li>
            <%else%>
              <li><%= link_to("トップページ","/")%></li>
              <li><%= link_to("投稿","/quizzes/index")%></li>
            <%end%>
          </ul>
      </div>
    </div>
    <%= stylesheet_link_tag 'quizzes', media: 'all' %>
    <% if flash[:notice] %>
      <%= flash[:notice] %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/quizzes/index.html.erb
<body>
  <h1>クイズ一覧</h1>
  <!-- セレクトボタンを追加 -->
  <%= form_with url: "/quizzes/index", method: :post, local: true do %>
    <div class="select_button">
      <select name="select_option">
        <% ["全体", "数学", "国語", "その他"].each do |option| %>
          <option value="<%= option %>" <%= 'selected' if params[:select_option] == option %>><%= option %></option>
        <% end %>
      </select>
      <%= submit_tag "選択"%>
    </div>
  <% end %>

  <div class="quiz_main">

   <div class="quiz_options_container">
      <% @quiz.each do |quiz|%>
        <div class="quiz_option_2">
          <%= link_to quiz.title, quiz_path(quiz.id) %>
        </div>
     <% end %>
   </div>

     <!-- ページネーションのボタンを表示 -->
    <div class="quiz_button">
      <!-- 戻る ？以降は空の状態かセレクトが選択されたかのzでリンクを作っています-->
      <% if @prev_page%> 
        <%= link_to('戻る', "/quizzes/index?page=#{@prev_page}&select_option=#{params[:select_option]}")%>  
      <%end%>


      
      <!-- 次へボタン -->
      <% unless @is_last_page %>
        <%= link_to('次へ', "/quizzes/index?page=#{@next_page}&select_option=#{params[:select_option]}") %>
      <% end %>
    </div>

  </div>
  <div class="index_footer">
      
  </div>
</body>

app/views/quizzes/new.html.erb
<body>
  <div class="new_main">
    <div class="h1_title"><h1>Quizを投稿しよう!</h1></div>

  
    <%= form_with url: "/quizzes/create", method: :post, local: true do |f| %>
    
      <% if flash[:notice] %>
        <div class="messages">
           <%= flash[:notice] %>
        </div>
      <%end%>

      <div class="quiz_new">
        <p>セレクトボタン</p>
        <%= f.select :select_button_value, [["数学", "数学"], ["国語", "国語"], ["その他", "その他"]], { prompt: "選択してください" }, class: "form-control" %>

        <div class="new_title">
          <p>題名</p>
          <small>50文字以内で入力をお願いします</small>
          <%= f.text_field :title, placeholder: "タイトルを入力", class: "form-control" %>
        </div>

        <div class="new_problem">
          <p>問題集</p>
          <small>250文字以内で入力をお願いします</small>
         <%= f.text_area :question, placeholder: "問題文を入力", class: "form-control" %>
        </div>

        <div class="new_request_1">
          <p>回答</p>
          <small>50文字以内で入力をお願いします</small>
          <%= f.text_field :answer_1, placeholder: "回答 1 を入力", class: "form-control" %>
        </div>

        <div class="new_request_2">
          <p>回答</p>
          <small>50文字以内で入力をお願いします</small>
          <%= f.text_field :answer_2, placeholder: "回答 2 を入力", class: "form-control" %>
        </div>

        <div class="new_correct_answer">
          <p>！正解！</p>
          <small>50文字以内で入力をお願いします</small>
          <%= f.text_field :user_answer, placeholder: "正解を入力", class: "form-control" %>
        </div>
        <div class="new_select_button">
          
        </div>

        <p><%= f.submit "クイズを作成", class: "btn btn-primary" %></p>
      </div>
    <% end %>
  </div>
  <div class="quiz_footer">
  </div>
</body>

app/views/quizzes/show.html.erb
<h1> クイズ </h1>

<body>
  <div class="shwo_main">
    
    <div class="quizzwa_show">
    <div class="quiz_question"><%= @quiz.question %></div>

    <!-- fom_ウィズ  URLの開いたクイズIDのアンサー情報を送りたい--> 
      <%= form_with(url: "/quizzes/#{@quiz.id}/check_answer", method: :post) do |form|%>
        <% @options.each do |option| %> 
          <div class="option"> 
            <%= form.radio_button :selected_answer, option %>
            <%= label_tag "selected_answer_#{option}", option %><br>
          </div>
        <% end %>
        <div class="answer"><%= submit_tag '答えを送信' %></div>
      <% end %>
    </div>
    

    <!-- <%= form_tag("/quizzes/#{@quiz.id}/check_answer", method: :post) do %>
        <% @options.each do |option| %> 
          <div class="option">
            <%= radio_button_tag 'selected_answer', option %> 
            <%= option %><br>
          </div>
        <% end %>
        <div class="answer"><%= submit_tag '答えを送信' %></div>
      <% end %>
    </div> -->
      
    

    <!-- ランキング -->
    <% if @quiz_result.present? %>
    <div class="quiz-result-container">
        <% @quiz_result.each_with_index do |result, index| %>
          <p>
            <span class="index_xxx">順位 <%= index + 1%></span>
            <span class="username"><%= result.user.name %> </span>
            <span class="time-spent">tame:<%= Time.at(result.time_spent.to_i).utc.strftime("%H:%M:%S") %></span>
          </p>
        <% end %>
      <%end%>
    </div>
    
     








  </div>
</body>

app/views/user/index.html.erb
<h1>ユーザー 一覧</h1>

<body>
  <div class="userindex_main">
    <% @users.each do |user| %>
      <div class="user_index_score">
       <div class="name"> <%= user.name%> </div>
       <div class="score"><%= user.score%> </div> 
       <div class="time"><%= Time.at(user.total_time).utc.strftime("%H:%M:%S")%></div>
      </div>
    <%end%>
  </div>




  <div class="userindex_footer">
  </div>
</body>

app/views/user/login.html.erb
<body>
  <div class="user_main">
    <div class="form-heading">ログイン画面</div>

    <div class="form-body">
      <%= form_tag("/login") do%>
        <p>名前</p>
        <input name="name">
        <p>メールアドレス</p>
        <input name= "email">
        <p><input type="submit" value="ログイン"></p>
      <%end%>
    </div>
  </div>
</body>


<div class="user_footer">
</div>

app/views/user/new.html.erb
<h1>新規ユーザー登録</h1>